baseURL: https://hugo-toha.github.io
languageCode: en-us
title: "Dan's Portfolio"
theme: 'toha'

languages:
  en:
    languageName: English
    weight: 1
  
  cn:
    languageName: 简体中文
    weight: 2

  kr:
    languageName: 한국어
    weight: 3

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params: 
  
  gitRepo: https://github.com/Yeonhoon/portfolio.git
  
  logo:
    main: images/default-hero.jpg
  
  enableBlogPost: true
  
  enableTOC: true
  
  newsletter:
    enable: true